title: JJ's GitHub Page
author: Jongjin Kim(@jkim205)
email: jkim205@crimson.ua.edu
description: > # this means to ignore newlines until "baseurl:"
  I will be the master of my GitHub Page.

# social links
twitter_username: themavine
github_username:  jkim205

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
